# Generated by Django 4.1.3 on 2022-12-02 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('horas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fechaingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrolamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idasignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.asignaturas')),
                ('idestudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estudiante')),
            ],
        ),
    ]
